CREATE OR REPLACE PROCEDURE "SCOTT"."P_EMP_BY_EMPNO"
(v_empNo IN EMP.EMPNO%TYPE, v_name OUT EMP.ENAME%TYPE, v_sal OUT EMP.SAL%TYPE)
AS
BEGIN
  SELECT ENAME,SAL INTO v_name,v_sal FROM EMP WHERE EMPNO=v_empNo;
  DBMS_OUTPUT.PUT_LINE('P_EMP_BY_EMPNO, ENAME: ' || v_name || ', SAL: ' || v_sal);
END;